// Code generated by tools/ast.py. DO NOT EDIT MANUALLY.

package ast

import "mejroslav/golox/v2/internal/pkg/golox/token"

type Stmt interface {
	Accept(visitor StmtVisitor) (any, error)
}

type StmtVisitor interface {
	VisitBlockStmt(stmt *Block) (any, error)
	VisitClassStmt(stmt *Class) (any, error)
	VisitExpressionStmt(stmt *Expression) (any, error)
	VisitFunctionStmt(stmt *Function) (any, error)
	VisitReturnStmt(stmt *Return) (any, error)
	VisitIfStmt(stmt *If) (any, error)
	VisitWhileStmt(stmt *While) (any, error)
	VisitBreakStmt(stmt *Break) (any, error)
	VisitPrintStmt(stmt *Print) (any, error)
	VisitVarStmt(stmt *Var) (any, error)
}

type Block struct {
	Statements []Stmt
}

func (node *Block) Accept(visitor StmtVisitor) (any, error) {
	return visitor.VisitBlockStmt(node)
}

type Class struct {
	Name       *token.Token
	Superclass *Variable
	Methods    []Function
}

func (node *Class) Accept(visitor StmtVisitor) (any, error) {
	return visitor.VisitClassStmt(node)
}

type Expression struct {
	Expression Expr
}

func (node *Expression) Accept(visitor StmtVisitor) (any, error) {
	return visitor.VisitExpressionStmt(node)
}

type Function struct {
	Name   *token.Token
	Params []*token.Token
	Body   []Stmt
}

func (node *Function) Accept(visitor StmtVisitor) (any, error) {
	return visitor.VisitFunctionStmt(node)
}

type Return struct {
	Keyword *token.Token
	Value   Expr
}

func (node *Return) Accept(visitor StmtVisitor) (any, error) {
	return visitor.VisitReturnStmt(node)
}

type If struct {
	Condition  Expr
	ThenBranch Stmt
	ElseBranch Stmt
}

func (node *If) Accept(visitor StmtVisitor) (any, error) {
	return visitor.VisitIfStmt(node)
}

type While struct {
	Condition Expr
	Body      Stmt
}

func (node *While) Accept(visitor StmtVisitor) (any, error) {
	return visitor.VisitWhileStmt(node)
}

type Break struct {
	Keyword *token.Token
}

func (node *Break) Accept(visitor StmtVisitor) (any, error) {
	return visitor.VisitBreakStmt(node)
}

type Print struct {
	Expression Expr
}

func (node *Print) Accept(visitor StmtVisitor) (any, error) {
	return visitor.VisitPrintStmt(node)
}

type Var struct {
	Name        *token.Token
	Initializer Expr
}

func (node *Var) Accept(visitor StmtVisitor) (any, error) {
	return visitor.VisitVarStmt(node)
}
