// Code generated by tools/ast.py. DO NOT EDIT MANUALLY.

package golox

type Expr interface {
	Accept(visitor ExprVisitor) (any, error)
}

type ExprVisitor interface {
	VisitBinaryExpr(expr *Binary) (any, error)
	VisitCallExpr(expr *Call) (any, error)
	VisitGetExpr(expr *Get) (any, error)
	VisitSetExpr(expr *Set) (any, error)
	VisitThisExpr(expr *This) (any, error)
	VisitGroupingExpr(expr *Grouping) (any, error)
	VisitLiteralExpr(expr *Literal) (any, error)
	VisitLogicalExpr(expr *Logical) (any, error)
	VisitUnaryExpr(expr *Unary) (any, error)
	VisitVariableExpr(expr *Variable) (any, error)
	VisitAssignExpr(expr *Assign) (any, error)
}

type Binary struct {
	Left Expr
	Operator *Token
	Right Expr
}

func (node *Binary) Accept(visitor ExprVisitor) (any, error) {
	return visitor.VisitBinaryExpr(node)
}

type Call struct {
	Callee Expr
	Paren *Token
	Arguments []Expr
}

func (node *Call) Accept(visitor ExprVisitor) (any, error) {
	return visitor.VisitCallExpr(node)
}

type Get struct {
	Object Expr
	Name *Token
}

func (node *Get) Accept(visitor ExprVisitor) (any, error) {
	return visitor.VisitGetExpr(node)
}

type Set struct {
	Object Expr
	Name *Token
	Value Expr
}

func (node *Set) Accept(visitor ExprVisitor) (any, error) {
	return visitor.VisitSetExpr(node)
}

type This struct {
	Keyword *Token
}

func (node *This) Accept(visitor ExprVisitor) (any, error) {
	return visitor.VisitThisExpr(node)
}

type Grouping struct {
	Expression Expr
}

func (node *Grouping) Accept(visitor ExprVisitor) (any, error) {
	return visitor.VisitGroupingExpr(node)
}

type Literal struct {
	Value any
}

func (node *Literal) Accept(visitor ExprVisitor) (any, error) {
	return visitor.VisitLiteralExpr(node)
}

type Logical struct {
	Left Expr
	Operator *Token
	Right Expr
}

func (node *Logical) Accept(visitor ExprVisitor) (any, error) {
	return visitor.VisitLogicalExpr(node)
}

type Unary struct {
	Operator *Token
	Right Expr
}

func (node *Unary) Accept(visitor ExprVisitor) (any, error) {
	return visitor.VisitUnaryExpr(node)
}

type Variable struct {
	Name *Token
}

func (node *Variable) Accept(visitor ExprVisitor) (any, error) {
	return visitor.VisitVariableExpr(node)
}

type Assign struct {
	Name *Token
	Value Expr
}

func (node *Assign) Accept(visitor ExprVisitor) (any, error) {
	return visitor.VisitAssignExpr(node)
}

