// Code generated by tools/ast.py. DO NOT EDIT MANUALLY.

package golox

type Expr interface {
	Accept(visitor ExprVisitor) (any, error)
}

type ExprVisitor interface {
	VisitBinaryExpr(expr *Binary) (any, error)
	VisitGroupingExpr(expr *Grouping) (any, error)
	VisitLiteralExpr(expr *Literal) (any, error)
	VisitUnaryExpr(expr *Unary) (any, error)
	VisitVariableExpr(expr *Variable) (any, error)
}

type Binary struct {
	Left     Expr
	Operator *Token
	Right    Expr
}

func (node *Binary) Accept(visitor ExprVisitor) (any, error) {
	return visitor.VisitBinaryExpr(node)
}

type Grouping struct {
	Expression Expr
}

func (node *Grouping) Accept(visitor ExprVisitor) (any, error) {
	return visitor.VisitGroupingExpr(node)
}

type Literal struct {
	Value any
}

func (node *Literal) Accept(visitor ExprVisitor) (any, error) {
	return visitor.VisitLiteralExpr(node)
}

type Unary struct {
	Operator *Token
	Right    Expr
}

func (node *Unary) Accept(visitor ExprVisitor) (any, error) {
	return visitor.VisitUnaryExpr(node)
}

type Variable struct {
	Name Token
}

func (node *Variable) Accept(visitor ExprVisitor) (any, error) {
	return visitor.VisitVariableExpr(node)
}
