// Code generated by tools/ast.py. DO NOT EDIT MANUALLY.

package golox

type Stmt interface {
	Accept(visitor StmtVisitor) (any, error)
}

type StmtVisitor interface {
	VisitExpressionStmt(stmt *Expression) (any, error)
	VisitPrintStmt(stmt *Print) (any, error)
}

type Expression struct {
	Expression Expr
}

func (node *Expression) Accept(visitor StmtVisitor) (any, error) {
	return visitor.VisitExpressionStmt(node)
}

type Print struct {
	Expression Expr
}

func (node *Print) Accept(visitor StmtVisitor) (any, error) {
	return visitor.VisitPrintStmt(node)
}

