// Code generated by tools/ast.py. DO NOT EDIT MANUALLY.

package golox

type Stmt interface {
	Accept(visitor StmtVisitor) (any, error)
}

type StmtVisitor interface {
	VisitBlockStmt(stmt *Block) (any, error)
	VisitExpressionStmt(stmt *Expression) (any, error)
	VisitIfStmt(stmt *If) (any, error)
	VisitPrintStmt(stmt *Print) (any, error)
	VisitVarStmt(stmt *Var) (any, error)
}

type Block struct {
	Statements []Stmt
}

func (node *Block) Accept(visitor StmtVisitor) (any, error) {
	return visitor.VisitBlockStmt(node)
}

type Expression struct {
	Expression Expr
}

func (node *Expression) Accept(visitor StmtVisitor) (any, error) {
	return visitor.VisitExpressionStmt(node)
}

type If struct {
	Condition Expr
	Thenbranch Stmt
	Elsebranch Stmt
}

func (node *If) Accept(visitor StmtVisitor) (any, error) {
	return visitor.VisitIfStmt(node)
}

type Print struct {
	Expression Expr
}

func (node *Print) Accept(visitor StmtVisitor) (any, error) {
	return visitor.VisitPrintStmt(node)
}

type Var struct {
	Name Token
	Initializer Expr
}

func (node *Var) Accept(visitor StmtVisitor) (any, error) {
	return visitor.VisitVarStmt(node)
}

