# Create code for AST classes in Go.

import argparse

def generate_ast(output_dir: str) -> str:

    define_ast(output_dir, "expr", [
        "Binary   : Left Expr, Operator *token.Token, Right Expr",
        "Call     : Callee Expr, Paren *token.Token, Arguments []Expr",
        "Get      : Object Expr, Name *token.Token",
        "Set      : Object Expr, Name *token.Token, Value Expr",
        "Super    : Keyword *token.Token, Method *token.Token",
        "This     : Keyword *token.Token",
        "Grouping : Expression Expr",
        "Literal  : Value any",
        "Logical  : Left Expr, Operator *token.Token, Right Expr",
        "Unary    : Operator *token.Token, Right Expr",
        "Variable : Name *token.Token",
        "Assign   : Name *token.Token, Value Expr",
    ])

    define_ast(output_dir, "stmt", [
        "Block     : Statements []Stmt",
        "Class    : Name *token.Token, Superclass *Variable, Methods []Function",
        "Expression : Expression Expr",
        "Function   : Name *token.Token, Params []*token.Token, Body []Stmt",
        "Return    : Keyword *token.Token, Value Expr",
        "If        : Condition Expr, ThenBranch Stmt, ElseBranch Stmt",
        "While     : Condition Expr, Body Stmt",
        "Break     : Keyword *token.Token",
        "Print     : Expression Expr",
        "Var       : Name *token.Token, Initializer Expr",
    ])

def define_ast(output_dir: str, file: str, types: list[str]) -> None:
    path = f"{output_dir}/{file}.go"
    cls = file.capitalize()
    with open(path, "w") as f:
        f.write("// Code generated by tools/ast.py. DO NOT EDIT MANUALLY.\n\n")
        f.write("package ast\n\n")
        f.write("import \"mejroslav/golox/v2/internal/pkg/golox/token\"\n\n")
        f.write("type " + cls + " interface {\n")
        f.write("\tAccept(visitor " + cls + "Visitor) (any, error)\n")
        f.write("}\n\n")

        # Visitor interface
        f.write("type " + cls + "Visitor interface {\n")
        for type_def in types:
            class_name = type_def.split(":")[0].strip()
            f.write(f"\tVisit{class_name}{cls}({cls.lower()} *{class_name}) (any, error)\n")
        f.write("}\n\n")

        # AST classes
        for type_def in types:
            class_name, fields = type_def.split(":")
            class_name = class_name.strip()
            fields = fields.strip()

            f.write(f"type {class_name} struct {{\n")
            for field in fields.split(","):
                name, type_ = field.strip().split(" ")
                f.write(f"\t{name} {type_}\n")
            f.write("}\n\n")

            # Accept method
            f.write(f"func (node *{class_name}) Accept(visitor {cls}Visitor) (any, error) {{\n")
            f.write(f"\treturn visitor.Visit{class_name}{cls}(node)\n")
            f.write("}\n\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        "-o",
        default="internal/pkg/golox/ast",
        type=str,
        required=False,
        help="The output directory to write the generated AST code to.",
    )
    args = parser.parse_args()

    ast = generate_ast(args.output)
    print(f"AST classes generated successfully to {args.output}.")
